export { CTASection } from "./CTASection"
export { DestinationsPreview } from "./DestinationsPreview"
export { FeaturedTours } from "./FeaturedTours"
export { HeroVideoParallax } from "./HeroVideoParallax"
export { ParallaxBand } from "./ParallaxBand"
export { PartnerLogosSection } from "./PartnerLogosSection"
export { TestimonialsSection } from "./TestimonialsSection"
